#!/bin/sh

. panel_config
. panel_colors

pkill lemonbar

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Change this when swapping to different monitorzzzz
bspc config -m DVI-1 top_padding $((PANEL_HEIGHT + PANEL_YOFFSET))
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

while true; do
    echo -e "TIME$(date +' %_H:%M')"
    sleep $REFRESH_CLOCK
done > "$PANEL_FIFO" &

while true; do
    echo -e "DATE$(date +'%a, %b %_d')"
    sleep $REFRESH_DATE
done > "$PANEL_FIFO" &

while true; do
    if [[ $(pgrep -cx mpd) -gt 0 ]]; then
        MEDIA_TITLE=$(mpc current)
        if [[ -z $MEDIA_TITLE ]]; then
            medialine=""
        else
            MEDIA_TIME=$(mpc status | head -n 2 | tail -n 1 | awk '{print $3'})
            if mpc status | grep -q 'paused'; then
                medialine="%{A:mpc -q play:}$MEDIA_TITLE [%{F$COLOR_MEDIA_TIME}$MEDIA_TIME%{F-}]%{A}"
            else
                medialine="%{A:mpc -q pause:}$MEDIA_TITLE [%{F$COLOR_MEDIA_TIME}$MEDIA_TIME%{F-}]%{A}"
            fi
        fi
    fi
    echo -e "MUSIC$medialine"
    sleep $REFRESH_MEDIA
done > "$PANEL_FIFO" &


panel_bar < "$PANEL_FIFO" | lemonbar \
    -a 20 \
    -n "$PANEL_WM_NAME" \
    -g "$PANEL_WIDTH""x$PANEL_HEIGHT""+$PANEL_XOFFSET""+$PANEL_YOFFSET" \
    -o 0 \
    -f "$PANEL_FONT" \
    -o -2 \
    -f "$PANEL_FONT2" \
    -F "$COLOR_DEFAULT_FG" \
    -B "$COLOR_DEFAULT_BG" | sh &

wait
