#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# some apps
feh --bg-scale "$HOME/Images/Wallpapers/spirited-away1.jpg" &
dunst --config "$HOME/.config/dunst/dunstrc" &
picom &
xsettingsd &
redshift &
"$HOME/.config/polybar/launch.sh" &

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

bspc monitor -d 1 2 3 4 5

rule feh                    state=floating
rule Gpick                  state=floating
rule firefox:Places         state=floating
rule Zathura                state=tiled
rule mpv                    state=floating

config border_width          0
config border_radius         15
config window_gap            16

config split_ratio           0.50
config borderless_monocle    true
config gapless_monocle       true

config top_padding	     0
config left_padding	     0
config right_padding	     0
config bottom_padding 	     0

config pointer_modifier	     mod4
config focus_follows_pointer false
# config focused_border_color    "#AB47BC"
# config normal_border_color     "#292D3E"
# config active_border_color     "#292D3E"
