#!/bin/bash

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 61AFEF
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Oblogout state=floating fullscreen=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='3'

bspc monitor DVI-0 -d 1 3 5
bspc monitor DVI-1 -d 2 4 6

bspc config normal_border_color '#5C6370'
bspc config active_border_color '#5C6370'
bspc config focused_border_color '#61AFEF'

xsetroot -cursor_name left_ptr &
# compton -b
~/.config/lemonbar/panel &
sxhkd &
mpd &
redshift &
