#!/bin/bash

lock="󰌾"
logout="󰩈"
shutdown="󰐥"
reboot="󰜉"
sleep="󰤄"

options="$lock\n$logout\n$shutdown\n$reboot\n$sleep"
 
selected=$(echo -e "$options" | rofi -dmenu -p "Power" -theme "~/.config/rofi/powermenu.rasi")

if [ "$selected" == "$lock" ]; then
    betterlockscreen --lock
elif [ "$selected" == "$logout" ]; then
    bspc quit
elif [ "$selected" == "$shutdown" ]; then
    systemctl poweroff
elif [ "$selected" == "$reboot" ]; then
    systemctl reboot
elif [ "$selected" == "$sleep" ]; then
    amixer set Master mute
    systemctl suspend
else
    exit 0
fi
