
[font]
size = 11

[font.bold]
family = "Iosevka Mayukai Codepro"
style = "Bold"

[font.bold_italic]
family = "Iosevka Mayukai Codepro"
style = "Bold Italic"

[font.italic]
family = "Iosevka Mayukai Codepro"
style = "Italic"

[font.normal]
family = "Iosevka Mayukai Codepro"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = true

[window.padding]
x = 8
y = 8

[general]
import = ["/home/m1tix/.config/alacritty/colors.toml"]
